sudo: false
language: ruby
script: make travisPublish
branches:
  only:
  - develop
env:
  global:
  - GH_REF: github.com/Widen/widen.github.io
  - secure: HBo2et59JYhV6RfZzeLGuoLEWbzaCq4uRvEvrHAYnHlSRHVHpIIbXhn3Fr6HktA9gFqT3rXfFTe6oFkyxZ5iLEtIM5sgClZzaqtUkpCzBORkmxMVyZK4090K4xSQa6KxrQFQeyIgp5i6LF0q9F+K52Fkd7WtvPiI/SeYjUM+n60=
