title: "Widen Dev"
description: "An open source software initiative."
timezone: "America/Chicago"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://widen.github.io"
email: "devrel@widen.com"

# DEFAULTS
defaults:
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

permalink: "/blog/:year/:month/:day/:title"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
kramdown:
  smart: true
  input: GFM
  syntax_highlighter: rouge
assets:
  compress:
    css:  sass
    js:   uglifier
