title: "Widen Engineering"
description: "The blog of the Widen Engineering Team."
timezone: "America/Chicago"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://engineering.widen.com"
email: "engineering@widen.com"
disqus: widen-engineering

# DEFAULTS
defaults:
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

permalink: "/blog/:title/"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
kramdown:
  smart: true
  input: GFM
  syntax_highlighter: rouge
assets:
  compress:
    css:  sass
    js:   uglifier
  sources:
    - _assets/images
    - _assets/stylesheets
    - _assets/fonts
exclude: [Makefile, Rakefile, Gemfile, Gemfile.lock, README.md, vendor]
repository: widen/widen.github.io
google_analytics_code: UA-1206716-19
plugins: ['jekyll-git_metadata', 'jekyll-github-metadata', 'jekyll-sitemap']
