title: "Widen Dev"
description: "An open source software initiative."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://widen.github.io"
email: "devrel@widen.com"

# DEFAULTS
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
kramdown:
  smart: true
  input: GFM
  syntax_highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
